export * from "./landingPage";
export { Title } from "./landingPage";
export * from "./ui";
export { Header } from "./header";
export { ProductTour } from "./detailPage";
export * from "./detailPage";
export * from "./footer";
export * from "./login";
export * from "./aboutUs";
export * from "./callUs";
export * from "./hotel";
export * from "./tourPlace";
export * from "./travel-insurance";
export * from "./itinerary";
export { CategoryMenu, CategoryMenuMobileItem } from "./landingPage";
export * from "./allproduct";
export * from "./userPanel";
